"""
ComfyUI-SAM-Body4D Nodes

Aggregates all node mappings from processing modules.
"""

from .processing.load_model import NODE_CLASS_MAPPINGS as LOAD_MODEL_MAPPINGS
from .processing.load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_MODEL_DISPLAY_MAPPINGS
from .processing.image_sequence import NODE_CLASS_MAPPINGS as IMAGE_SEQ_MAPPINGS
from .processing.image_sequence import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_SEQ_DISPLAY_MAPPINGS
from .processing.body4d_process import NODE_CLASS_MAPPINGS as PROCESS_MAPPINGS
from .processing.body4d_process import NODE_DISPLAY_NAME_MAPPINGS as PROCESS_DISPLAY_MAPPINGS
from .processing.skeleton_extract import NODE_CLASS_MAPPINGS as SKELETON_MAPPINGS
from .processing.skeleton_extract import NODE_DISPLAY_NAME_MAPPINGS as SKELETON_DISPLAY_MAPPINGS
from .processing.fbx_export import NODE_CLASS_MAPPINGS as EXPORT_MAPPINGS
from .processing.fbx_export import NODE_DISPLAY_NAME_MAPPINGS as EXPORT_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOAD_MODEL_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_SEQ_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROCESS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SKELETON_MAPPINGS)
NODE_CLASS_MAPPINGS.update(EXPORT_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_MODEL_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_SEQ_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROCESS_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SKELETON_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EXPORT_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
